// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yaocldiyslrhntdvrwlg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlhb2NsZGl5c2xyaG50ZHZyd2xnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3NzkzMzEsImV4cCI6MjA1NDM1NTMzMX0.AGBf14rfquFgAYWRVXFNfYW-P6eMc0rOiVHn17wcRLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);